# Generated by Django 3.2.5 on 2021-09-11 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0012_auto_20210706_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmessage',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='updated',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='commentmessage',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentmessage',
            name='post',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='barber.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
