# Generated by Django 3.2.5 on 2021-09-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0013_auto_20210911_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmessage',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='created_on',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='updated_on',
            new_name='updated',
        ),
    ]
