# Generated by Django 3.2.5 on 2021-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0014_auto_20210911_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
