# Generated by Django 3.2.5 on 2021-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0015_auto_20210912_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
