# Generated by Django 3.2.5 on 2021-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0016_auto_20210912_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='message',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
